version: "3.8"

services:
  influxdb:
    image: "influxdb:2.4"
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=garden
      - DOCKER_INFLUXDB_INIT_PASSWORD=garden_password
      - DOCKER_INFLUXDB_INIT_ORG=garden
      - DOCKER_INFLUXDB_INIT_BUCKET=garden
  grafana:
    image: "grafana/grafana"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    ports:
      - 9093:3000
    networks:
      - influxdb

networks:
  influxdb:

volumes:
  influxdb:
  grafana_data:
