version: "3.8"

services:
  prometheus:
    image: "prom/prometheus"
    restart: always
    networks:
      - prometheus
    ports: 
      - 9092:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
  pushgateway:
    image: "prom/pushgateway"
    restart: always
    ports:
      - 9091:9091
    networks:
      - prometheus
  grafana:
    image: "grafana/grafana"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    ports:
      - 9093:3000
    networks:
      - prometheus

networks:
  prometheus:

volumes:
  prometheus:
  grafana_data:
